### ISSUE TITLE
it runs twice?

### ISSUE THREAD

**Issue by fredgrott** [frencojobs/derry#45]
Hello, so I installed it making sure I had my 3 path envs set ie dart bin, flutter bin, and pubcache bin.

When I launch derry in android studio terminal it will run everything twice...

typical output via terminal in as is:

D:\fredgrttsstuff\ForkProjects\foundations_of_flutter\uml>derry build
uml@1.0.0+1 build
$ pub global run dcdg --output=uml.puml 

$ echo web output of uml

web output of uml
uml@1.0.0+1 build
$ pub global run dcdg --output=uml.puml 

$ echo web output of uml

web output of uml

D:\fredgrttsstuff\ForkProjects\foundations_of_flutter\uml>

any idea why it executes twice?

not an immediate deal breaker but when I ad in everything else it might be as it will then take twice as long due to executing twice.

Thanks for such a good tool, I like thus far as it's very useful for the use cases I have.

**Comment by fredgrott** [comment]
note, the only thing I can think of is that my dart install is in the flutter sdk. But not sure of why that matters as far as everything executing twice.  Executing dcdg by itself without derry works as it only executes once. My derry.yaml is:

uml:
  - pub global run dcdg --output=uml.puml
  - echo web output of uml

build:
  - $uml

**Comment by frencojobs** [comment]
Can you reproduce it again? Maybe something went wrong during the process and caused the error but I couldn't reproduce the error with all the similar details you provide.

As expected for this config file,
```yaml
uml:
  - pub global run dcdg --output=uml.puml
  - echo web output of uml
build:
  - $uml
```
the output is
```bash
work/tmp/derry-issue-45 via  v2.12.0-259.0.dev took 2s

$ derry build
derry_issue_45@1.0.0+1 build
$ pub global run dcdg --output=uml.puml

$ echo web output of uml

web output of uml
```
Please let me know if the error happens again, or it's just an unreproducible one-time error.

The only path that matters is the pubcache bin, and it doesn't have anything to do with the issue. I also tried it in the Android Studio Terminal, and everything works just fine.

**Comment by fredgrott** [comment]
Okay found my problems:

1. had in pubspec the derry: path: stuff which is not needed
2. some versions of android studio goof upon path stuff so just did it from the terminal powershell and it worked fine only execute once..

Thanks again for a nice tool as it's less complicated than grinder...

Not sure why android studio terminalis goofing up will probably raise issue with android studio team

**Comment by YoussefRaafatNasry** [comment]
I have the same issue now, after upgrading to **flutter 2**.

I only have `flutter` and `pub-cache` in my PATH, the following error happens after tying to run a script _(it tried to run it again but didn't find the `pub` command)_.
And if I add `pub` to my PATH, the script now runs twice.


```shell
$ derry build
***@1.0.0+1 build
$ flutter pub get

Running "flutter pub get" in ***...                           17.8s
$ flutter pub run build_runner build

...

'pub' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by YoussefRaafatNasry** [comment]
I got it to run only once by changing the contents of this file:

`C:\Users\***\AppData\Local\Pub\Cache\bin\derry.bat`:

```bat
@echo off
dart "C:\Users\***\AppData\Local\Pub\Cache\global_packages\derry\bin\derry.dart-2.12.0.snapshot" %*
```

But how can we get it fixed without editing the file manually?

**Comment by frencojobs** [comment]
The snapshot is generated by pub and I think it's rather caused by the conflict between `dart pub` and `flutter pub` (not sure though). Thank you very much for the reports but I don't think there's anything I can do with derry about that.

My advice is to never use `flutter pub` except in a flutter project. Use fvm if possible and always and only use `pub` for installing global packages.
