### ISSUE TITLE
Failed to precompile derry in Flutter 2.2.0

### ISSUE THREAD

**Issue by Brazol** [frencojobs/derry#49]
I get this error when trying to activate derry after upgrading to Flutter 2.2.0

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/5622717/119670200-fc94fa80-be38-11eb-9b94-aaf12accefb2.png">

**Comment by xalikoutis** [comment]
same here

**Comment by frencojobs** [comment]
Duplicate of #47
