### ISSUE TITLE
Failed to load dynamic library executor_mac64.dylib - incompatible architecture (have 'x86_64', need 'arm64e') (mac m1)

### ISSUE THREAD

**Issue by HugoHeneault** [frencojobs/derry#58]
Hello there 👋 

Thanks your `derry`! Such a cool tool. 

I'm having issues running it on my m1 macbook:

```
Invalid argument(s): Failed to load dynamic library '/Users/hugo/.pub-cache/hosted/pub.dartlang.org/derry-1.4.3/lib/src/blobs/executor_mac64.dylib': dlopen(/Users/hugo/.pub-cache/hosted/pub.dartlang.org/derry-1.4.3/lib/src/blobs/executor_mac64.dylib, 0x0001): tried: '/Users/hugo/.pub-cache/hosted/pub.dartlang.org/derry-1.4.3/lib/src/blobs/executor_mac64.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/executor_mac64.dylib' (no such file)
```

Even when running in a Rosetta terminal, I still encounter this issue. 

How could I help you make derry run on m1 arch?

Thanks!

**Comment by Arinono** [comment]
Hey 👋 

That's a late response, but if anyone is still interested, here is what I did.
Long story short, you need to recompile the project yourself (on your m1 machine), then activate it from local.

```bash
# Once cloned and inside the repo directory
$>

**Comment by aarajput** [comment]
I am also facing same issue on my Macbook air M1.

**Comment by aarajput** [comment]
@Arinono , Now i am getting below error after following your steps.F

<img width="1380" alt="Screenshot 2022-05-16 at 11 28 43 AM" src="https://user-images.githubusercontent.com/16102514/168532219-bb01ba57-cab9-4814-9975-efc451086a11.png">

**Comment by Arinono** [comment]
@aarajput I don't know the reason, and I don't have enough information to guess, but it seems that you either:
- did not rebuild the lib with rust
- did not copy the built lib before activating
- have an environment that made you build the lib with the wrong target architecture

I'm not sure how I can provide more help but to advise you to make sure that you followed the steps and that your environment is properly configured (Terminal, rust/dart config, ...)

Everything I tried lead to it working with me:

<details><summary>Using a terminal through Rosetta</summary>

![Screenshot 2022-05-16 at 10 52 10](https://user-images.githubusercontent.com/10957531/168555825-28ebdb16-e743-43db-8313-c5d3e33f1fb6.png)

</details>

<details><summary>Building the lib targeting the wrong arch</summary>

![Screenshot 2022-05-16 at 10 53 14](https://user-images.githubusercontent.com/10957531/168556108-a40ca3d6-395a-4cfb-9657-befd702415a1.png)

</details>

**Comment by aarajput** [comment]
@Arinono , i found the issue. My terminal's rosetta was enabled when i installed cargo.
So, i uninstalled rustup, then switched off rosetta and reinstalled cargo using rustup and followed your steps and it worked. Thanks.

**Comment by om-ha** [comment]
Seconded 👍 👀

**Comment by frencojobs** [comment]
Hey everyone, [I'm back](https://frenco.dev/blog/i-am-back). I'm so sorry for disappearing for such a long time.

If you're still using derry, I just finished working on [v1.5](#69) that'll add support for M1 Macs. I'll close this issue automatically once it's released. Feel free to reopen it if the it's still not working on M1 machines because I haven't got the chance to test it on a real M1 machine.
