### ISSUE TITLE
Add option to use a custom yaml file for storing scripts

### ISSUE THREAD

**Issue by Luckey-Elijah** [frencojobs/derry#60]
Currently `derry` searches for the root directory's `pubspec.yaml` files and reads the `scripts:` there. Perhaps there could be an option to pass your own `script.yaml` or `derry.yaml`  for maintaining scripts in a separate file.

**Comment by frencojobs** [comment]
The first section on [README documentation](https://github.com/frencojobs/derry#api-documentation) here.

**Comment by Luckey-Elijah** [comment]
Thanks! Somehow missed that 😅
